name: androidci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - name: set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          java-version: '11'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Test
        run: |
          ./gradlew :core:test
          ./gradlew :processor:test
          ./gradlew :android:testDebugUnitTest
